# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o52hw0miR3_rEda-lWEY3BUfgta51iGG
"""

import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# ── CONFIG ──────────────────────────────────────────────────────────
db_user   = 'etl_user1'
db_pass   = '3December2000@'
db_host   = '127.0.0.1'
db_port   = '5432'
db_name   = 'etl_demo'
csv_path  = r'C:\Users\palak\Desktop\week1\data\superstore_clean.csv'

# percent-encode special chars
db_pass_enc = quote_plus(db_pass)

# ── ENGINE SETUP ───────────────────────────────────────────────────
conn_str = (
    f'postgresql+psycopg2://{db_user}:{db_pass_enc}'
    f'@{db_host}:{db_port}/{db_name}'
)
engine = create_engine(conn_str)

# ── LOAD FUNCTION ───────────────────────────────────────────────────
def load_raw():
    print(f"Reading CSV from `{csv_path}`…")
    df = pd.read_csv(csv_path, parse_dates=['order_date','ship_date'])
    print(f"Truncating existing data in sales_raw…")
    with engine.begin() as conn:
        conn.execute(text("TRUNCATE TABLE public.sales_raw;"))
        print(f"Loading {len(df)} rows into sales_raw…")
        df.to_sql(
            'sales_raw',
            con=conn,
            if_exists='append',
            index=False,
            method='multi',
            chunksize=1000
        )
    print(f"✅ Loaded {len(df)} rows into sales_raw")

if __name__ == '__main__':
    load_raw()