# -*- coding: utf-8 -*-
"""notify.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0UuXSdYfp4r-F6pG878UAcGDGzERam9
"""

# scripts/notify.py

import os
import smtplib
from email.message import EmailMessage

def send_email(subject: str, body: str):
    # Read credentials from environment variables
    EMAIL_ADDRESS = os.environ.get('verma.rohan.2000@gmail.com')
    EMAIL_PASSWORD = os.environ.get('ALERT_PWD')
    if not EMAIL_ADDRESS or not EMAIL_PASSWORD:
        raise RuntimeError("Set ALERT_EMAIL and ALERT_PWD env vars for notifications.")

    msg = EmailMessage()
    msg['From']    = EMAIL_ADDRESS
    msg['To']      = EMAIL_ADDRESS
    msg['Subject'] = subject
    msg.set_content(body)

    # Connect to Gmail SMTP (or your provider)
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        smtp.send_message(msg)